### ISSUE TITLE
Problème installation Casino

### ISSUE THREAD

**Issue by kyo06** [badetitou/BL-ToolKit#19]
Bonjour,

j'ai trouvé votre projet de recherche très intéressant.
J'ai souhaité testé mais je suis bloqué à l'installation :

![image](https://github.com/badetitou/Casino/assets/230858/570417ca-140f-4bc8-8f23-61ab173b3759)

Pourriez vous m'aider s'il vous plait ?

Cordialement,
Dr. Mohammed REZGUI

**Comment by badetitou** [comment]
Hello

This is an issue with a conflict with XMLParser. My advice is to use the
`onConflictUseIncoming` method for the configuration.

I have updated the readme accordingly to:

```st
Metacello new
  githubUser: 'badetitou' project: 'Casino' commitish: 'v2.0.24' path: 'src';
  baseline: 'Casino';
  onConflictUseIncoming;
  load
```


It will be a pleasure to discuss with you about this project. 
Note that even if we use this project in a daily basis at Berger-Levrault, it might not be easy to understand and adapt if you have no prior knowledge of [Moose](https://modularmoose.org/) and [Pharo](https://pharo.org/)
