### ISSUE TITLE
More claryifing guide to migrate an exisisting GWT application to Angular2

### ISSUE THREAD

**Issue by lupohirp** [badetitou/BL-ToolKit#7]
Hello, 

i'm requesting your help for helping to migrate an exisiting GWT application to Angular2. I've saw your tool, but unfortunately i don't know anything about Moose and Pharo language. 
Howewer i understood that this could help me to migrate the UI easily. 

For example, i dont' understand this step:

'path/to/model.mse' asFileReference readStreamDo: [ :stream | famixModel := FAMIXModel new importFromMSEStream: stream ]

what is this 'path/to/model.mse'  ? 

Please, can you help me?

**Comment by badetitou** [comment]
Hello,

Before all, note that this piece of work is a bit specialized for the Berger-Levrault company. But most of the code can be reused to migrate your application. Another super generic GWT importer exists here https://github.com/badetitou/Casino-GWT-Importer but with no knowledge about Moose and Pharo, it could be difficult to adapt the code to your context.

Migration is not an easy task, and you'll not find any magic tool.
To learn about Pharo, you should have a look at: https://mooc.pharo.org/, and discuss with the RMoD research team (https://rmod.gitlabpages.inria.fr/website/) who started this migration project.
About Moose, the main reference is https://modularmoose.org/

About your question: 

`path/to/model.mse` is a file path (used in your computer, such as (in windows), `C:/Users/`).
`model.mse` is a file created with the [VerveineJ tool](https://modularmoose.org/moose-wiki/Developers/Parsers/VerveineJ)

We now use a JSON format, and I'd just updated the readme accordingly (with a note about using VerveineJ).

In the file, you have a description of a model (this migration project uses [metamodeling](https://en.wikipedia.org/wiki/Metamodeling))

So, the line 
`'path/to/model.mse' asFileReference readStreamDo: [ :stream | famixModel := FAMIXModel new importFromMSEStream: stream ]`
imports a model inside the Moose environment

**Comment by NicolasAnquetil** [comment]
Hello lupohirp,
we are a research ream working with companies on software analysis tools.
The work on GWT migration was such a project.
If you want more information on Moose and/or pharo, you can contact us: nicolas.anquetil@inria.fr
