### ISSUE TITLE
generation of import for inner type does not always work

### ISSUE THREAD

**Issue by badetitou** [badetitou/BL-ToolKit#8]
In the above generated DTO example, `MyClass` and `AbstractStuff` are well imported but not `LiquidationAcompteGWT`.

We should check and test this case

```ts
import { JsonProperty, JsonClassType } from "@outfoxx/jackson-js";

import {
    AbstractStuff,
    MyClass
} from "..";

export class MYDTO extends AbstractStuff {

    @JsonProperty()
    @JsonClassType({ type: () => [Map, [MyClass, Array, [LiquidationAcompteGWT]]] })
    regroupementRubriqueCdpForLiquidation: Map<MyClass, Array<LiquidationAcompteGWT>>;
}
```

**Comment by Gabriel-Darbord** [comment]
Fixed [here](https://github.com/badetitou/Casino/commit/0b6f5047e2c90ab5f610be6d9991904d8851ea80). We might have to look back into it if we want to handle parameterized types.
