### ISSUE TITLE
CSNService should have a parent and children

### ISSUE THREAD

**Issue by badetitou** [badetitou/BL-ToolKit#9]
Following their potentiel source structure (Java classes)
A CSNService can have parentService and childrenservices.
We should make this modification at the meta-model level

**Comment by Gabriel-Darbord** [comment]
Change made [here](https://github.com/badetitou/Casino/commit/cc62f5d5d627b9d4620b6c871872b38be8a73fd0). CSNService now has *childServices* and *parentService* properties. It's the importer's duty to fill them up.
